### ISSUE TITLE
Stretch armv8 jobs fail on apt since the official release

### ISSUE THREAD

**Issue by mikaelarguedas** [ros-infrastructure/ros_buildfarm#455]
Stretch armv8 jobs have been consistently failing in the past few days. It seemed to have appeared just after Stretch was released. I didn't look into the issue yet and thus I'm opening this for tracking it

```
[0mInvoking 'apt-get update'
Hit:1 http://repositories.ros.org/ubuntu/building stretch InRelease
Ign:2 http://cdn-fastly.deb.debian.org/debian stretch InRelease
Ign:3 http://cdn-fastly.deb.debian.org/debian stretch InRelease
Hit:4 http://cdn-fastly.deb.debian.org/debian stretch Release
Hit:5 http://cdn-fastly.deb.debian.org/debian stretch Release
Err:5 http://cdn-fastly.deb.debian.org/debian stretch Release
  Failed to stat - stat (2: No such file or directory)
Reading package lists...
E: The repository 'http://deb.debian.org/debian stretch Release' does no longer have a Release file.
Invocation failed without any known error condition, printing all lines to debug known error detection:
  1 'Hit:1 http://repositories.ros.org/ubuntu/building stretch InRelease'
  2 'Ign:2 http://cdn-fastly.deb.debian.org/debian stretch InRelease'
  3 'Ign:3 http://cdn-fastly.deb.debian.org/debian stretch InRelease'
  4 'Hit:4 http://cdn-fastly.deb.debian.org/debian stretch Release'
  5 'Hit:5 http://cdn-fastly.deb.debian.org/debian stretch Release'
  6 'Err:5 http://cdn-fastly.deb.debian.org/debian stretch Release'
  7 '  Failed to stat - stat (2: No such file or directory)'
  8 'Reading package lists...'
  9 'E: The repository 'http://deb.debian.org/debian stretch Release' does no longer have a Release file.'
None of the following known errors were detected:
  1 'Failed to fetch'
  2 'Hash Sum mismatch'
  3 'Unable to locate package'
  4 'is not what the server reported'
```
Example of failing job: http://build.ros.org/view/Lbin_dsv8_dSv8/job/Lbin_dsv8_dSv8__marti_data_structures__debian_stretch_arm64__binary/3/console

**Comment by tfoote** [comment]
This looks like an issue with the server/cdn.

For: https://deb.debian.org/debian I get
```
Not Found

The requested URL /debian was not found on this server.

Apache Server at deb.debian.org Port 443
```

https://deb.debian.org/debian/ redirects to https://cdn-aws.deb.debian.org/debian/ which has real content.

**Comment by dirk-thomas** [comment]
This has nothing to do with ssl. If you append the missing trailing slash to the http url you see the same behavior.

**Comment by sloretz** [comment]
Seen a second time http://build.ros.org/job/Lbin_dsv8_dSv8__urdf_parser_plugin__debian_stretch_arm64__binary/4/console

```
23:25:44 [0mInvoking 'apt-get update'
23:25:46 Hit:1 http://repositories.ros.org/ubuntu/building stretch InRelease
23:25:47 Ign:2 http://cdn-fastly.deb.debian.org/debian stretch InRelease
23:25:47 Ign:3 http://cdn-fastly.deb.debian.org/debian stretch InRelease
23:25:47 Hit:4 http://cdn-fastly.deb.debian.org/debian stretch Release
23:25:47 Hit:5 http://cdn-fastly.deb.debian.org/debian stretch Release
23:25:47 Err:5 http://cdn-fastly.deb.debian.org/debian stretch Release
23:25:47   Failed to stat - stat (2: No such file or directory)
23:26:02 Reading package lists...
23:26:02 E: The repository 'http://httpredir.debian.org/debian stretch Release' does no longer have a Release file.
23:26:02 Invocation failed without any known error condition, printing all lines to debug known error detection:
23:26:02   1 'Hit:1 http://repositories.ros.org/ubuntu/building stretch InRelease'
23:26:02   2 'Ign:2 http://cdn-fastly.deb.debian.org/debian stretch InRelease'
23:26:02   3 'Ign:3 http://cdn-fastly.deb.debian.org/debian stretch InRelease'
23:26:02   4 'Hit:4 http://cdn-fastly.deb.debian.org/debian stretch Release'
23:26:02   5 'Hit:5 http://cdn-fastly.deb.debian.org/debian stretch Release'
23:26:02   6 'Err:5 http://cdn-fastly.deb.debian.org/debian stretch Release'
23:26:02   7 '  Failed to stat - stat (2: No such file or directory)'
23:26:02   8 'Reading package lists...'
23:26:02   9 'E: The repository 'http://httpredir.debian.org/debian stretch Release' does no longer have a Release file.'
23:26:02 None of the following known errors were detected:
23:26:02   1 'Failed to fetch'
23:26:02   2 'Hash Sum mismatch'
23:26:02   3 'Unable to locate package'
23:26:02   4 'is not what the server reported'
```

**Comment by dirk-thomas** [comment]
Likely addressed by #458.

**Comment by mikaelarguedas** [comment]
Waiting for a rebuild of all jobs previously failing to see if #458 fixed the issue or if any other action needs to be taken

**Comment by mikaelarguedas** [comment]
While we see a lot less failures since #458 . It looks like `apt update` still fails fairly often when hitting the `contrib` and `non-free` arm64 repositories. Doesn't look to be related to the machine running the job given that the three following ones were ran on different machines.
http://build.ros.org/view/Lbin_dsv8_dSv8/job/Lbin_dsv8_dSv8__vision_visp__debian_stretch_arm64__binary/6/console
http://build.ros.org/view/Lbin_dsv8_dSv8/job/Lbin_dsv8_dSv8__phidgets_imu__debian_stretch_arm64__binary/7/console
http://build.ros.org/view/Lbin_dsv8_dSv8/job/Lbin_dsv8_dSv8__combined_robot_hw_tests__debian_stretch_arm64__binary/10/console

**Comment by tfoote** [comment]
So fastly seems to be the default but there's also a cloudfront mirror: https://cloudfront.debian.net/ which I expect will be faster on EC2, being an Amazon product.

**Comment by tfoote** [comment]
I haven't had a chance to watch it fully, but this seems like a good resource to understand the new cdn approach.

**Comment by mikaelarguedas** [comment]
I gave a try to cloudfront mirror on the job that fail last night using [this branch](https://github.com/ros-infrastructure/ros_buildfarm/compare/cloudfront_debian_mirror) and it seems that both jobs passed ([1](http://build.ros.org/view/Lbin_dsv8_dSv8/job/Lbin_dsv8_dSv8__urdf_tutorial__debian_stretch_arm64__binary/20/console) and [2](http://build.ros.org/view/Lbin_dsv8_dSv8/job/Lbin_dsv8_dSv8__urdf_sim_tutorial__debian_stretch_arm64__binary/2/console)). It's definitely not enough points to draw any conclusion but I'll keep rerunning failing jobs to use that branch to see if it consistently passes.

Talking with @tfoote yesterday we were also wondering if clearing the list between retries would help (`apt-get clean && rm -rf /var/lib/apt/lists/`). I think it's always good to do to be sure to have the latest. But thinking about it a bit more, I'm not sure this will solve the issue of getting a corrupted file because apt must be downloading and overwriting them otherwise the retry on `Hash Sum Mismatch` would never have a different outcome on any job. So my guess is that some Debian mirrors have wonky arm files and we repeatedly download the same bad files.

> I haven't had a chance to watch it fully, but this seems like a good resource to understand the new cdn approach. https://debconf16.debconf.org/talks/97/

Nice ! I'll try to have a look in the near future.

**Comment by mikaelarguedas** [comment]
Actually cloudfront looks promising, usually failing jobs retriggered on the same machine would keep failing. With that change a job [previously failing](http://build.ros.org/job/Lbin_dsv8_dSv8__desktop_full__debian_stretch_arm64__binary/18) just [passed](http://build.ros.org/job/Lbin_dsv8_dSv8__desktop_full__debian_stretch_arm64__binary/19) on the same machine

**Comment by dirk-thomas** [comment]
If the retries fail for the same reason could this also be due to the proxy we are using which might not re-fetch the resource but return the same broken result over and over?

**Comment by tfoote** [comment]
I don't think it's the proxy. We checked and we're forcing a refresh of all content after 1 minute: https://github.com/ros-infrastructure/buildfarm_deployment/blob/master/slave/manifests/site.pp#L182 And the 10 retries takes over 2 minutes. And we get different results within even one set of retries.

```
00:04:12.877 [0mInvoking 'apt-get update'
00:04:13.987 Hit:1 http://repositories.ros.org/ubuntu/building stretch InRelease
00:04:14.488 Ign:2 http://cdn-fastly.deb.debian.org/debian stretch InRelease
00:04:14.489 Ign:3 http://cdn-fastly.deb.debian.org/debian stretch InRelease
00:04:14.518 Hit:4 http://cdn-fastly.deb.debian.org/debian stretch Release
00:04:14.531 Get:5 http://cdn-fastly.deb.debian.org/debian stretch Release [113 kB]
00:04:14.713 Get:6 http://cdn-fastly.deb.debian.org/debian stretch Release.gpg [3,108 B]
00:04:19.851 Hit:8 http://cdn-fastly.deb.debian.org/debian stretch/contrib arm64 Packages
00:04:19.860 Hit:9 http://cdn-fastly.deb.debian.org/debian stretch/non-free arm64 Packages
00:04:19.899 Err:8 http://cdn-fastly.deb.debian.org/debian stretch/contrib arm64 Packages
00:04:19.899   Hash Sum mismatch
00:04:19.900   Hashes of expected file:
00:04:19.900    - Filesize:176201 [weak]
00:04:19.901    - SHA256:f6aab1f66f22cfc252c049b399fd0fc261392bf3c16216bec12c3c54c97c654e
00:04:19.901    - MD5Sum:60cb1d7a3b15c013996d711a7614b8d6 [weak]
00:04:19.901   Hashes of received file:
00:04:19.902    - SHA256:0d2889d2988fd5f3841583db31fef0abcdb5c82b830f19c1c1b53878d3fea41a
00:04:19.902    - MD5Sum:3e17d8d5f93698606aa4aa4368f3debc [weak]
00:04:19.902    - Filesize:72430 [weak]
00:04:19.903   Release file created at: Sat, 17 Jun 2017 08:44:51 +0000
00:04:19.909 Err:9 http://cdn-fastly.deb.debian.org/debian stretch/non-free arm64 Packages
00:04:19.910   
00:04:19.998 Fetched 117 kB in 6s (19.1 kB/s)
00:04:27.962 Reading package lists...
00:04:28.100 E: Failed to fetch store:/var/lib/apt/lists/partial/deb.debian.org_debian_dists_stretch_contrib_binary-arm64_Packages.gz  Hash Sum mismatch
00:04:28.101    Hashes of expected file:
00:04:28.101     - Filesize:176201 [weak]
00:04:28.102     - SHA256:f6aab1f66f22cfc252c049b399fd0fc261392bf3c16216bec12c3c54c97c654e
00:04:28.102     - MD5Sum:60cb1d7a3b15c013996d711a7614b8d6 [weak]
00:04:28.102    Hashes of received file:
00:04:28.103     - SHA256:0d2889d2988fd5f3841583db31fef0abcdb5c82b830f19c1c1b53878d3fea41a
00:04:28.103     - MD5Sum:3e17d8d5f93698606aa4aa4368f3debc [weak]
00:04:28.103     - Filesize:72430 [weak]
00:04:28.104    Release file created at: Sat, 17 Jun 2017 08:44:51 +0000
00:04:28.104 E: Failed to fetch store:/var/lib/apt/lists/partial/deb.debian.org_debian_dists_stretch_non-free_binary-arm64_Packages.gz  
00:04:28.104 E: Some index files failed to download. They have been ignored, or old ones used instead.
00:04:28.113 
00:04:28.113 Hash Sum mismatchInvocation failed due to the following known error conditions: , Failed to fetch
00:04:28.113 
00:04:28.113 Reinvoke 'apt update' (2/10) after sleeping 9 seconds
00:04:37.123 Invoking 'apt-get update'
00:04:37.856 Hit:1 http://repositories.ros.org/ubuntu/building stretch InRelease
00:04:38.007 Ign:2 http://cdn-fastly.deb.debian.org/debian stretch InRelease
00:04:38.008 Ign:3 http://cdn-fastly.deb.debian.org/debian stretch InRelease
00:04:38.059 Hit:4 http://cdn-fastly.deb.debian.org/debian stretch Release
00:04:38.120 Get:5 http://cdn-fastly.deb.debian.org/debian stretch Release [113 kB]
00:04:38.139 Get:6 http://cdn-fastly.deb.debian.org/debian stretch Release.gpg [3,108 B]
00:04:43.796 Ign:8 http://cdn-fastly.deb.debian.org/debian stretch/non-free arm64 Packages
00:04:43.899 Hit:9 http://cdn-fastly.deb.debian.org/debian stretch/contrib arm64 Packages
00:04:43.947 Err:9 http://cdn-fastly.deb.debian.org/debian stretch/contrib arm64 Packages
00:04:43.947   Hash Sum mismatch
00:04:43.948   Hashes of expected file:
00:04:43.948    - Filesize:176201 [weak]
00:04:43.948    - SHA256:f6aab1f66f22cfc252c049b399fd0fc261392bf3c16216bec12c3c54c97c654e
00:04:43.949    - MD5Sum:60cb1d7a3b15c013996d711a7614b8d6 [weak]
00:04:43.949   Hashes of received file:
00:04:43.949    - SHA256:0d2889d2988fd5f3841583db31fef0abcdb5c82b830f19c1c1b53878d3fea41a
00:04:43.949    - MD5Sum:3e17d8d5f93698606aa4aa4368f3debc [weak]
00:04:43.950    - Filesize:72430 [weak]
00:04:43.950   Release file created at: Sat, 17 Jun 2017 08:44:51 +0000
00:04:43.995 Fetched 117 kB in 6s (18.6 kB/s)
00:04:52.141 Reading package lists...
00:04:52.274 E: Failed to fetch store:/var/lib/apt/lists/partial/deb.debian.org_debian_dists_stretch_contrib_binary-arm64_Packages.gz  Hash Sum mismatch
00:04:52.275    Hashes of expected file:
00:04:52.275     - Filesize:176201 [weak]
00:04:52.276     - SHA256:f6aab1f66f22cfc252c049b399fd0fc261392bf3c16216bec12c3c54c97c654e
00:04:52.276     - MD5Sum:60cb1d7a3b15c013996d711a7614b8d6 [weak]
00:04:52.277    Hashes of received file:
00:04:52.277     - SHA256:0d2889d2988fd5f3841583db31fef0abcdb5c82b830f19c1c1b53878d3fea41a
00:04:52.277     - MD5Sum:3e17d8d5f93698606aa4aa4368f3debc [weak]
00:04:52.278     - Filesize:72430 [weak]
00:04:52.278    Release file created at: Sat, 17 Jun 2017 08:44:51 +0000
00:04:52.279 E: Some index files failed to download. They have been ignored, or old ones used instead.
00:04:52.286 
00:04:52.286 Hash Sum mismatchInvocation failed due to the following known error conditions: , Failed to fetch
00:04:52.286 
00:04:52.287 Reinvoke 'apt update' (3/10) after sleeping 11 seconds
00:05:03.301 Invoking 'apt-get update'
00:05:04.317 Hit:2 http://repositories.ros.org/ubuntu/building stretch InRelease
00:05:04.319 Ign:1 http://cdn-fastly.deb.debian.org/debian stretch InRelease
00:05:04.335 Ign:3 http://cdn-fastly.deb.debian.org/debian stretch InRelease
00:05:04.355 Hit:4 http://cdn-fastly.deb.debian.org/debian stretch Release
00:05:04.394 Get:5 http://cdn-fastly.deb.debian.org/debian stretch Release [113 kB]
00:05:04.563 Get:6 http://cdn-fastly.deb.debian.org/debian stretch Release.gpg [3,108 B]
00:05:10.177 Ign:8 http://cdn-fastly.deb.debian.org/debian stretch/non-free arm64 Packages
00:05:10.275 Hit:9 http://cdn-fastly.deb.debian.org/debian stretch/contrib arm64 Packages
00:05:10.278 Ign:8 http://deb.debian.org/debian stretch/non-free arm64 Packages
00:05:10.325 Err:9 http://cdn-fastly.deb.debian.org/debian stretch/contrib arm64 Packages
00:05:10.325   Hash Sum mismatch
00:05:10.326   Hashes of expected file:
00:05:10.326    - Filesize:176201 [weak]
00:05:10.326    - SHA256:f6aab1f66f22cfc252c049b399fd0fc261392bf3c16216bec12c3c54c97c654e
00:05:10.326    - MD5Sum:60cb1d7a3b15c013996d711a7614b8d6 [weak]
00:05:10.326   Hashes of received file:
00:05:10.326    - SHA256:0d2889d2988fd5f3841583db31fef0abcdb5c82b830f19c1c1b53878d3fea41a
00:05:10.327    - MD5Sum:3e17d8d5f93698606aa4aa4368f3debc [weak]
00:05:10.327    - Filesize:72430 [weak]
00:05:10.327   Release file created at: Sat, 17 Jun 2017 08:44:51 +0000
00:05:10.746 Fetched 117 kB in 6s (17.7 kB/s)
00:05:19.180 Reading package lists...
00:05:19.307 E: Failed to fetch http://cdn-fastly.deb.debian.org/debian/dists/stretch/non-free/binary-arm64/Packages.gz  Could not open file /var/lib/apt/lists/partial/deb.debian.org_debian_dists_stretch_non-free_binary-arm64_Packages.gz - open (13: Permission denied) [IP: 151.101.40.204 80]
00:05:19.308 E: Failed to fetch store:/var/lib/apt/lists/partial/deb.debian.org_debian_dists_stretch_contrib_binary-arm64_Packages.gz  Hash Sum mismatch
00:05:19.308    Hashes of expected file:
00:05:19.308     - Filesize:176201 [weak]
00:05:19.308     - SHA256:f6aab1f66f22cfc252c049b399fd0fc261392bf3c16216bec12c3c54c97c654e
00:05:19.308     - MD5Sum:60cb1d7a3b15c013996d711a7614b8d6 [weak]
00:05:19.308    Hashes of received file:
00:05:19.309     - SHA256:0d2889d2988fd5f3841583db31fef0abcdb5c82b830f19c1c1b53878d3fea41a
00:05:19.309     - MD5Sum:3e17d8d5f93698606aa4aa4368f3debc [weak]
00:05:19.309     - Filesize:72430 [weak]
00:05:19.309    Release file created at: Sat, 17 Jun 2017 08:44:51 +0000
00:05:19.309 E: Some index files failed to download. They have been ignored, or old ones used instead.
00:05:19.316 
00:05:19.316 Hash Sum mismatchInvocation failed due to the following known error conditions: , Failed to fetch
00:05:19.316 
00:05:19.316 Reinvoke 'apt update' (4/10) after sleeping 13 seconds
00:05:32.331 Invoking 'apt-get update'
00:05:33.053 Hit:1 http://repositories.ros.org/ubuntu/building stretch InRelease
00:05:33.440 Ign:2 http://cdn-fastly.deb.debian.org/debian stretch InRelease
00:05:33.441 Ign:3 http://cdn-fastly.deb.debian.org/debian stretch InRelease
00:05:33.489 Hit:4 http://cdn-fastly.deb.debian.org/debian stretch Release
00:05:33.550 Get:5 http://cdn-fastly.deb.debian.org/debian stretch Release [113 kB]
00:05:33.577 Get:6 http://cdn-fastly.deb.debian.org/debian stretch Release.gpg [3,108 B]
00:05:38.204 Hit:8 http://cdn-fastly.deb.debian.org/debian stretch/non-free arm64 Packages
00:05:38.231 Hit:9 http://cdn-fastly.deb.debian.org/debian stretch/contrib arm64 Packages
00:05:38.251 Err:8 http://cdn-fastly.deb.debian.org/debian stretch/non-free arm64 Packages
00:05:38.251   Hash Sum mismatch
00:05:38.251   Hashes of expected file:
00:05:38.251    - Filesize:222075 [weak]
00:05:38.251    - SHA256:a07317b5f74ba433c790f5c18e37c2a0f097a72d78fbe003ee3588f3cfe012f3
00:05:38.251    - MD5Sum:b650dc75f778a94560b3e6bbc1bd81a2 [weak]
00:05:38.251   Hashes of received file:
00:05:38.251    - SHA256:6e6261a94c5b2b402d3602cc383ca42c02613766de95f6b0e6ce9a17fb97aeb4
00:05:38.251    - MD5Sum:30cc7e4fcedb8eb9b2520a8111be5ce8 [weak]
00:05:38.251    - Filesize:92209 [weak]
00:05:38.251   Release file created at: Sat, 17 Jun 2017 08:44:51 +0000
00:05:38.255 Err:9 http://cdn-fastly.deb.debian.org/debian stretch/contrib arm64 Packages
00:05:38.256   
00:05:38.323 Fetched 117 kB in 5s (21.7 kB/s)
00:05:46.448 Reading package lists...
00:05:46.554 E: Failed to fetch store:/var/lib/apt/lists/partial/deb.debian.org_debian_dists_stretch_non-free_binary-arm64_Packages.gz  Hash Sum mismatch
00:05:46.555    Hashes of expected file:
00:05:46.555     - Filesize:222075 [weak]
00:05:46.555     - SHA256:a07317b5f74ba433c790f5c18e37c2a0f097a72d78fbe003ee3588f3cfe012f3
00:05:46.556     - MD5Sum:b650dc75f778a94560b3e6bbc1bd81a2 [weak]
00:05:46.556    Hashes of received file:
00:05:46.556     - SHA256:6e6261a94c5b2b402d3602cc383ca42c02613766de95f6b0e6ce9a17fb97aeb4
00:05:46.556     - MD5Sum:30cc7e4fcedb8eb9b2520a8111be5ce8 [weak]
00:05:46.557     - Filesize:92209 [weak]
00:05:46.557    Release file created at: Sat, 17 Jun 2017 08:44:51 +0000
00:05:46.557 E: Failed to fetch store:/var/lib/apt/lists/partial/deb.debian.org_debian_dists_stretch_contrib_binary-arm64_Packages.gz  
00:05:46.558 E: Some index files failed to download. They have been ignored, or old ones used instead.
00:05:46.562 
00:05:46.562 Hash Sum mismatchInvocation failed due to the following known error conditions: , Failed to fetch
00:05:46.562 
00:05:46.563 Reinvoke 'apt update' (5/10) after sleeping 15 seconds
00:06:01.563 Invoking 'apt-get update'
00:06:02.433 Hit:3 http://repositories.ros.org/ubuntu/building stretch InRelease
00:06:02.435 Ign:1 http://cdn-fastly.deb.debian.org/debian stretch InRelease
00:06:02.436 Ign:2 http://cdn-fastly.deb.debian.org/debian stretch InRelease
00:06:02.462 Hit:4 http://cdn-fastly.deb.debian.org/debian stretch Release
00:06:02.480 Get:5 http://cdn-fastly.deb.debian.org/debian stretch Release [113 kB]
00:06:02.506 Get:6 http://cdn-fastly.deb.debian.org/debian stretch Release.gpg [3,108 B]
00:06:08.111 Hit:8 http://cdn-fastly.deb.debian.org/debian stretch/non-free arm64 Packages
00:06:08.120 Ign:9 http://cdn-fastly.deb.debian.org/debian stretch/contrib arm64 Packages
00:06:08.172 Err:8 http://cdn-fastly.deb.debian.org/debian stretch/non-free arm64 Packages
00:06:08.173   Hash Sum mismatch
00:06:08.173   Hashes of expected file:
00:06:08.173    - Filesize:222075 [weak]
00:06:08.173    - SHA256:a07317b5f74ba433c790f5c18e37c2a0f097a72d78fbe003ee3588f3cfe012f3
00:06:08.173    - MD5Sum:b650dc75f778a94560b3e6bbc1bd81a2 [weak]
00:06:08.173   Hashes of received file:
00:06:08.173    - SHA256:6e6261a94c5b2b402d3602cc383ca42c02613766de95f6b0e6ce9a17fb97aeb4
00:06:08.173    - MD5Sum:30cc7e4fcedb8eb9b2520a8111be5ce8 [weak]
00:06:08.173    - Filesize:92209 [weak]
00:06:08.173   Release file created at: Sat, 17 Jun 2017 08:44:51 +0000
00:06:08.232 Fetched 117 kB in 5s (19.5 kB/s)
00:06:18.563 Reading package lists...
00:06:18.698 E: Failed to fetch store:/var/lib/apt/lists/partial/deb.debian.org_debian_dists_stretch_non-free_binary-arm64_Packages.gz  Hash Sum mismatch
00:06:18.698    Hashes of expected file:
00:06:18.698     - Filesize:222075 [weak]
00:06:18.698     - SHA256:a07317b5f74ba433c790f5c18e37c2a0f097a72d78fbe003ee3588f3cfe012f3
00:06:18.699     - MD5Sum:b650dc75f778a94560b3e6bbc1bd81a2 [weak]
00:06:18.699    Hashes of received file:
00:06:18.699     - SHA256:6e6261a94c5b2b402d3602cc383ca42c02613766de95f6b0e6ce9a17fb97aeb4
00:06:18.699     - MD5Sum:30cc7e4fcedb8eb9b2520a8111be5ce8 [weak]
00:06:18.700     - Filesize:92209 [weak]
00:06:18.700    Release file created at: Sat, 17 Jun 2017 08:44:51 +0000
00:06:18.700 E: Some index files failed to download. They have been ignored, or old ones used instead.
00:06:18.707 
00:06:18.707 Hash Sum mismatchInvocation failed due to the following known error conditions: , Failed to fetch
00:06:18.707 
00:06:18.707 Reinvoke 'apt update' (6/10) after sleeping 17 seconds
00:06:35.730 Invoking 'apt-get update'
00:06:36.709 Hit:1 http://repositories.ros.org/ubuntu/building stretch InRelease
00:06:37.498 Ign:2 http://cdn-fastly.deb.debian.org/debian stretch InRelease
00:06:37.499 Ign:3 http://cdn-fastly.deb.debian.org/debian stretch InRelease
00:06:37.610 Hit:4 http://cdn-fastly.deb.debian.org/debian stretch Release
00:06:37.727 Hit:5 http://cdn-fastly.deb.debian.org/debian stretch Release
00:06:37.773 Ign:5 http://cdn-fastly.deb.debian.org/debian stretch Release
00:06:38.193 Hit:6 http://cdn-fastly.deb.debian.org/debian stretch/contrib all Packages
00:06:38.385 Hit:7 http://cdn-fastly.deb.debian.org/debian stretch/non-free all Packages
00:06:38.391 Hit:8 http://cdn-fastly.deb.debian.org/debian stretch/non-free arm64 Packages
00:06:38.582 Hit:9 http://cdn-fastly.deb.debian.org/debian stretch/contrib arm64 Packages
00:06:49.657 Reading package lists...
00:06:49.745 W: The repository 'http://deb.debian.org/debian stretch Release' does not have a Release file.
```

**Comment by dirk-thomas** [comment]
This output is actually interesting. It even suggests that the proxy might be involved here. The compressed output looks like this:

* First invocation of `apt update`: fails with "Hash Sum mismatch"
* Reinvoke 'apt update' (2/10) after sleeping 9 seconds: fails with "Hash Sum mismatch"
* Reinvoke 'apt update' (3/10) after sleeping 11 seconds: fails with "Hash Sum mismatch"
* Reinvoke 'apt update' (4/10) after sleeping 13 seconds: fails with "Hash Sum mismatch"
* Reinvoke 'apt update' (5/10) after sleeping 15 seconds: fails with "Hash Sum mismatch"
* Reinvoke 'apt update' (6/10) after sleeping 17 seconds: :tada: succeeds

The interesting point is that the successful run happens 65 seconds after the initial failure. So it looks like that the first four retries might all be server from the proxy which returns the same file which has the hash sum mismatch from the first invocation. If that is the case the proxy behavior undermines the retry logic. Essentially we are not retrying 10 times but only 3 times. If that is the case we should either make the proxy drop that resource from the cache or if that is not possible extend the timeout for each retry to be bigger than the refresh threshold of the proxy.

**Comment by tfoote** [comment]
Totaling the sleep time isn't a good indicator of elapsed time which is what the cache timeout cares about. The failing updates themselves take as long as the sleeps. The first error happens at: 
 4:19 elapsed in the job. And the successful run starts at 6:35 notably more that the sleep timeout. And as I mentioned we get different results on the file size. 72430 for the first minute or so, then 92209 for the next minute. Then it passes. So it's likely that we are caching the content for 1 minute, but in this case we're still getting consecutive failures even after the proxy refreshes.

This suggests that we might want to consider slowing down our retries cycling. Unfortunately squid only takes the timeout in minutes so I don't know how to set it lower. And we also could try to figure out how to set cache information on the repository webserver, but I don't believe that's something reprepro supports and that would only work for our hosted repos. And either way it's optimizing the side effects of the bad return values from the apt repo. 

Also looking into this I checked and the size of the file expected is the `Packages` file inside the tarball hosted here: http://cdn-fastly.deb.debian.org/debian/dists/stretch/non-free/binary-arm64/Packages.gz 


```
$ ls -l Packages 
-rw-rw-r-- 1 tfoote tfoote 222075 Jul  7 16:23 Packages
tfoote@snowman:/tmp Last: [0] (0s Seconds)
$ md5sum Packages 
b650dc75f778a94560b3e6bbc1bd81a2  Packages
```
![image](https://user-images.githubusercontent.com/447804/27980222-51ff188c-6331-11e7-9955-3c8e8f210d9e.png)


And that file has been there since June 17th Stretch's release date which is approximately when we started having trouble. 


We just have to find the CDN node that's having trouble....

**Comment by mikaelarguedas** [comment]
When talking with @dirk-thomas offline, we figured that it could be a good idea (not necessarily only for this particular issue) to segregate our "known errors" into "will fail the retry if the proxy still has the resource" v.s "proxy doesn't impact the retries". And this way we could use a different time to sleep between retries for the first category (adding squid timeout to the time to wait?) and thus ensure that the retries are performing a different action.

I agree this is still partly to work around this specific issue but it would have the benefit of ensuring that the retries logic is actually retrying and not fetching the same corrupted resource half of the time.

**Comment by dirk-thomas** [comment]
In order to keep the usage of the proxy transparent it would be good to always check the URL upstream. Basically a threshold of zero minutes if that is possible.

Also has anyone made an effort to report this problem? That would probably the best approach to get a broken mirror fixed if that is actually the reason.

**Comment by tfoote** [comment]
I can't find a point of contact for the fastly CDN so I've asked Jeb who's listed as a point of contact for the cloudfront mirror if he can make a connection or provide any insight.

**Comment by tfoote** [comment]
I got some feedback from James:

> Sorry, I don't know anyone who is looking after Fastly. I have been seeing an increase in consistency errors on the mirror network that is the upstream of the CloudFront (AWS) CDN; some mirror sites (ie, upstream origin server(s)) were sending redirects to the CDN instead of serving content. I've just pulled cloudfront.debian.net form using ftp.debian.org as its upstream to ftp.us.debian.org to try and reduce the number of nodes that sit upstream (both are a pool of servers, but the US pool is obviously smaller than the global pool).
> 
> Often times the cached directory listing (auto index generated web page) does not accurately reflect the information of the files (objects) that would sit under that URL path, so looking at /debian/dists/stretch/non-free/binary-arm64/ may not show the actualy Packages.gz or xz that you're being served back - it may be an out of date index page, or the object at Packages.gz and Packages.xz may be out of date. These files need to be kept very fresh, and I dont know what Fastly admins are doing to do that.
> 
> 
> On the CloudFront CDN, I force the Time to Live (TTL) for paths in /debian/dists/ to be very short - sometimes as short as 5 minutes, where as the default would be 24 hours. If I didn't set it to 5 minutes for that path, then the request to get the directory listing may be done live against an origin in the case of a CDN CACHE MISS, but the next request to get Package.xz may be a CACHE HIT from a file that was uploaded 23 hours ago even through that's not the one you're after. There's a bunch of signed/checksummed files and the one that's 23 hours old may be out of date.
> 
> Hope that helps with some ideas. Use curl or wget, and look at the headers of each file you would request, and check the timestamps and cache hit/miss status (should be in the headers of the responses).

Based on that I'd suggest that we go ahead with #461 since James is monitoring theses issues.

**Comment by mikaelarguedas** [comment]
I'm going to close this now that #461 has merged.

Thanks @tfoote and @dirk-thomas for the follow-up on this. I'll monitor the jobs and reopen this if this issue still happens.

**Comment by mikaelarguedas** [comment]
Follow-up: After a full rebuild of Lunar we didnt face this issue a single time so I'd say it's safe to assume that switching to cloudfront solved this issue

**Comment by mikaelarguedas** [comment]
Actually we have several failures due to a corrupted deb `gnome-icon-theme`  on some fastly mirrors. Note: this package comes from the `main` repository so is not using the cloudfront mirrors introduced in #461:

Link to the currently impacted jobs:
http://build.ros.org/job/Lbin_dsv8_dSv8__image_cb_detector__debian_stretch_arm64__binary/6/
http://build.ros.org/job/Lbin_dsv8_dSv8__swri_geometry_util__debian_stretch_arm64__binary/4/
http://build.ros.org/view/Lbin_dsv8_dSv8/job/Lbin_dsv8_dSv8__moveit_ros_planning_interface__debian_stretch_arm64__binary/

**Comment by mikaelarguedas** [comment]
havent seen any failure since #467 and #468 got merged. Going to close this again and keep monitoring the jobs
